name: Pull Request

on:
  pull_request:
    branches: [main, decoupling, decoupling-bun-mock-server]

permissions:
  contents: read

jobs:
  setup-polytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci

      - name: Setup Polytest
        uses: aorumbayev/algokit-polytest/.github/actions/setup-polytest@feat/ghcr-and-shared-action

      - name: Validate polytest algod_client tests
        run: npm run polytest:validate-algod

  build-and-test:
    needs: setup-polytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Commit lint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint
        run: npm run lint --if-present

      - name: Check types
        run: npm run check-types --if-present

      # Start localnet for integration tests
      - name: Start LocalNet
        run: |
          pipx install algokit
          algokit localnet start
          npx --yes wait-on tcp:4001 -t 30000

      # Start mock servers using composite action
      - name: Start algod mock server
        uses: aorumbayev/algokit-polytest/.github/actions/run-mock-server@feat/ghcr-and-shared-action
        with:
          client: algod

      - name: Start indexer mock server
        uses: aorumbayev/algokit-polytest/.github/actions/run-mock-server@feat/ghcr-and-shared-action
        with:
          client: indexer

      - name: Start kmd mock server
        uses: aorumbayev/algokit-polytest/.github/actions/run-mock-server@feat/ghcr-and-shared-action
        with:
          client: kmd

      - name: Run tests
        run: npm run test --if-present -- --silent

      - name: Audit
        run: npm run audit

      - name: Build
        run: npm run build

  check-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Check docs are up to date
        run: |
          npm ci --ignore-scripts
          npm run generate:code-docs
          # Add untracked files as empty so they come up in diff
          git add -N .
          # Print changed files and error out if there are changes after generating docs
          git diff --exit-code --name-only
